# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_nbdev_hello_world.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_nbdev_hello_world.ipynb 2
def say_hello(to):
    """Say hello to somebody"""
    return f'Hello {to}!'

# %% ../nbs/00_nbdev_hello_world.ipynb 4
def foo(): pass
